# CGN-Curobo-Imit
name: FetchPtdImitCuroboCGN

defaults:
    - FetchPtdImitTwoStage
    - FetchPtdCuroboCGNBeta
    - _self_

viewer:
  camPos: [-2.0, 1.5, 2.5]
  camTar: [0, 0, 0.7]
  enable: True

# if given, will override the device setting in gym. 
env:
  numTasks: null
  enableDebugVis: False

  aggregateMode: 0
  aggregateBody: 30
  aggregateShape: 1000

  armControlType: joint  # options are {joint, osc}
  gripperControlType: velocity

  # set to True if you use camera sensors in the environment
  enableCameraSensors: True
  sim_delay_steps: True

  cam:
    width: 320
    height: 240

solution:
  ckpt_path: null
  video_freq: 8
  num_fetch_steps: 100
  impedance_control: false
  config: null


